variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  # -DinstallAtEnd=true -DdeployAtEnd=true
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

stages:
  - build
  - test
  - release
  - deploy
  - rollout

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/

docker-build:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jib:build
  only:
    - develop
    - master

dev-deploy:
  stage: rollout
  #  before_script:
  #    - ssh-keygen -R 192.168.2.93
  script:
    - ssh -tt -i DiTECT-Dev.pem ubuntu@192.168.2.93
    - docker pull containergui.internal.wings-ict-solutions.dev/ditect-service:latest
    - docker run -p8080:8080 -e'DB_HOST=172.18.0.2' containergui.internal.wings-ict-solutions.dev/ditect-service -d
  when: manual
# TODO: replace latest with tag version
