jwk-set-uri: ${JWK_URI:http://192.168.2.199:8080/auth/realms/ditect/protocol/openid-connect/certs}
allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}


spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: 27017
      database: ditect
      username: ${DB_USER:admin}
      password: ${DB_PASS:admin}
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:16MB}
      max-request-size: ${MAX_FILE_SIZE:16MB}

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: ${MNGM_PORT:8081}

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

logging:
  level:
    org:
      springframework:
        security: debug
        data: debug
